local_run: false

sim_ip: 10.10.1.1
cloud_ip: 10.10.1.2
edge_ip: 10.10.1.3

num_edges: 2
num_workers: 2

sim_port_cloud: 10000
sim_port_edge: 10001
sim_port_worker: 10002 
cloud_port: 50000
edge_ports:
  - 60000
  - 60001
  - 60002
  - 60003
  - 60004
  - 60005
  - 60006
  - 60007
  - 60008
  - 60009

max_cloud_gradients: 10
max_edge_gradients: 10

batch_size: 100
num_training_data: 50000
num_val_loss: 10000

num_epochs: 100

learning_rate: 0.0005

ROU_FILE: './osm_boston_common/osm.passenger.trips.xml'
NET_FILE: './osm_boston_common/osm.net.xml'
FCD_FILE: './osm_boston_common/osm_fcd.xml'
v2rsu: 100
